rm(list=ls())
setwd("~/Downloads")
library(cdcfluview)
library(imputeTS)
library(MMWRweek)
library(ggplot2)
library(zoo)
library(smooth)
library(Mcomp)
library(readxl)
library(egg)
library(lubridate)
library(cowplot)
library(gridExtra)
library(grid)
library(dplyr)

#data for plot 1a is unable to be made public

###plot 1b###
flu <- who_nrevss(region = "national", years = NULL)

#extract the 3 databases from flu list and make variables comparable#
dat1 <- as.data.frame(flu$combined_prior_to_2015_16) %>% 
  filter(year>1998) %>% 
  mutate(total_a = a_h1 + a_h3 + a_2009_h1n1 + a_subtyping_not_performed + a_unable_to_subtype,
         total_b = b,
         total_flu = total_a + total_b) %>% 
  select(wk_date, total_specimens, total_flu, total_a, a_h1, a_h3, a_2009_h1n1, total_b)
dat2 <- as.data.frame(flu$public_health_labs) %>% 
  mutate(total_a = a_2009_h1n1 + a_h3 + a_subtyping_not_performed,
         total_b = b+bvic+byam,
         total_flu = total_a + total_b,
         a_h1 = 0) %>% 
  select(wk_date, total_specimens, total_flu, total_a, a_h1, a_h3, a_2009_h1n1, total_b)
dat3 <- as.data.frame(flu$clinical_labs) %>% 
  mutate(total_flu = total_a + total_b,
         a_h3 = 0,
         a_2009_h1n1 = 0,
         a_h1 = 0) %>% 
  select(wk_date, total_specimens, total_flu, total_a, a_h1, a_h3, a_2009_h1n1, total_b)


##Extrapolating percents for A subtypes##
#calculating proportion positive for each flu subtype#

dat <- rbind(dat1, dat2, dat3) %>% group_by(wk_date) %>% summarize_all(sum) %>% ungroup %>% 
  arrange(wk_date) %>% 
  mutate(propa.h1 = a_h1/(a_2009_h1n1+a_h1+a_h3),
         propa.h1 = na_interpolation(propa.h1),
         propa.2009h1n1 = a_2009_h1n1/(a_2009_h1n1+a_h1+a_h3),
         propa.2009h1n1 = na_interpolation(propa.2009h1n1),
         propa.h3 = a_h3/(a_2009_h1n1+a_h1+a_h3),
         propa.h3 = na_interpolation(propa.h3),
         ah1.int = total_a*propa.h1,
         a2009h1n1.int = total_a*propa.2009h1n1,
         ah3.int = total_a*propa.h3,
         prop.pos = total_flu/total_specimens,
         prop.pos = ifelse(is.nan(prop.pos),0,prop.pos),
         prop.b = total_b/total_specimens,
         prop.b = ifelse(is.nan(prop.b),0,prop.b),
         prop.ah1 = ah1.int/total_specimens,
         prop.ah1 = ifelse(is.nan(prop.ah1),0, prop.ah1),
         prop.a2009 = a2009h1n1.int/total_specimens,
         prop.a2009 = ifelse(is.nan(prop.a2009),0,prop.a2009),
         prop.ah3 = ah3.int/total_specimens,
         prop.ah3 = ifelse(is.nan(prop.ah3),0,prop.ah3)) %>% 
  select(wk_date, total_specimens, total_flu, total_a, ah1.int, a2009h1n1.int, ah3.int, propa.h1, propa.2009h1n1, propa.h3, total_b,prop.pos, prop.b, prop.ah1, prop.ah3, prop.a2009)
write.csv(dat, "weekly-flu-subtypes.csv")

#calculating rolling average#
dat = read.csv("weekly-flu-subtypes.csv")
#this was the csv generated by the code above ^ -> can also be downloaded from https://github.com/lecohen/SARS-CoV-2_pandemic-to-endemic

dat = mutate(dat, threeweek_avg_prop.a2009= rollmean(prop.a2009, 3, align="center", fill=0))

dat_from_2009 <- dat[523:1208,,]
dat_from_2009$wk_date <- mdy(dat_from_2009$wk_date)
dat_from_2009$yr_date <- year(dat_from_2009$wk_date)

colors2 <- c("Three Week Rolling Average"="red","Confirmed H1N1 * 100 / Total Specimens Tested (Percent Positive)"="pink")

plot_h1n1_2009 <- ggplot(data=dat_from_2009)+
  theme_bw()+
  geom_col(aes(x=wk_date, y=prop.a2009*100), fill="pink") + 
  ggtitle("Seasons of Pandemic H1N1 in the US") + 
  ylab("Percent Positive (%)") + xlab("Date") + 
  theme(plot.title = element_text(hjust = 0.5, size = 11)) +
  geom_line(aes(x=wk_date, y = threeweek_avg_prop.a2009*100, color = "Three Week Rolling Average"), size = .75) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank()) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") + labs(color="Legend") + scale_color_manual(values = colors2) +
  theme(legend.title=element_blank())

#y axis = Confirmed H1N1 * 100 / Total Specimens Tested (Percent Positive)#

###plot 1c###
options(scipen=999)

#before continuing, download csv file (owid-covid-data) from https://github.com/lecohen/SARS-CoV-2_pandemic-to-endemic 
covid <- read.csv("owid-covid-data.csv")
which(covid$location=="United States")
##

#usa data#
covid_usa = covid[157920:158646,,]
#only including rows that have a non-NA number for tests_per_case
covid_usa$tests_per_case
colnames(covid_usa)
covid_usa_streamlined <- covid_usa[,c(4,6,33)]
covid_usa_streamlined$totalspecimenstested <- covid_usa_streamlined$new_cases * covid_usa_streamlined$tests_per_case  
covid_usa_streamlined$prop_covid <- covid_usa_streamlined$new_cases / covid_usa_streamlined$totalspecimenstested
covid_usa_streamlined <- mutate(covid_usa_streamlined, threeweek_avg_covid= rollmean(prop_covid, 21, align="center", fill=0)) 
covid_usa_streamlined$date <- as.Date(covid_usa_streamlined$date, "%m/%d/%y")
percent_covid <- covid_usa_streamlined$prop_covid * 100

colors3 <- c("Confirmed SARS-CoV-2 * 100 / Total Specimens Tested (Percent Positive)"="red","New Cases"="pink")

#max number of new cases is 1,368,165; min number of cases is 75
#sqrt(1368165)
#40/1169.686 = 0.034

covid_usa_streamlined$sqrt_new_cases <- sqrt(covid_usa_streamlined$new_cases)

plot_cov_2020 <-ggplot(data=covid_usa_streamlined)+
  theme_bw()+ geom_col(aes(x=date, y=(sqrt_new_cases*0.034)), fill="pink") + geom_line(aes(x=date, y = percent_covid, color = "Confirmed SARS-CoV-2 * 100 / Total Specimens Tested (Percent Positive)"), size = .75) +
  ggtitle("US SARS-CoV-2 Waves, 2020-2022") + 
  xlab("Date") + 
  theme(plot.title = element_text(hjust = 0.5, size = 11)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank()) +
  scale_y_continuous(name = "Percent Positive (%)", limits=c(0,40), breaks=c(0,10,20,30,40), sec.axis = sec_axis(~./.034, name=expression(sqrt("New Cases of SARS-CoV-2"))))+
  scale_x_date(date_breaks = "2 months", date_labels = "%b %Y") + labs(color="Legend") + scale_color_manual(values = colors3) +
  theme(legend.title=element_blank()) + theme(axis.text.x = element_text(angle = 90)) + theme(axis.text.y = element_text(size = 9)) 

#y axis = Confirmed SARS-CoV-2 * 100 / Total Specimens Tested (Percent Positive)#

#plot the three plots 
blankPlot <- ggplot()+geom_blank(aes(1,1)) + cowplot::theme_nothing()
blankPlot_label <- plot_grid(blankPlot)
top_plots <- plot_grid(plot_h1n1_2009 + theme(legend.justification = c(0,1)), labels = c('B'), label_size = 12)
g1 <- ggplotGrob(top_plots)
g2 <- ggplotGrob(plot_cov_2020)
g3 <- ggplotGrob(blankPlot)
blankPlot_label <- blankPlot_label + draw_figure_label(label = "C", fontface = "bold", position="top.right", size=12)
g4 <- ggplotGrob(blankPlot_label)
frame_g2 <- gtable_frame(g2, debug = FALSE, width=unit(.95,"null"))
frame_g3 <- gtable_frame(g3, debug = FALSE, width=unit(.001,"null"))
frame_g4 <- gtable_frame(g4, debug = FALSE, width=unit(5.1,"null"))

frame_combi <- gtable_frame(gtable_cbind(frame_g4,frame_g2,frame_g3),
                            width = unit(1,"null"),
                            height = unit(.33,"null"))
frame_g1  <-
  gtable_frame(
    g1,
    width = unit(1, "null"),
    height = unit(1, "null"),
    debug = FALSE
  )

grid.newpage()
all_frames <- gtable_rbind(frame_g1, frame_combi)
grid.draw(all_frames)

#Width = 2650 pixels, Height = 700 pixels
